#!/bin/bash

if [ ! -z $* ]; then
    export $*
fi

DBUSERNAME="root"
DBPASSWORD="12345678"
DBDELETEEXISTS=false
DBNAME="cloud_note_db"

TIMESTAMP=`date +%Y%m%d%H%M%S`  
DBLOG=dblog_${TIMESTAMP}.log;

if [ x"$delete_exists" = xtrue ]; then
    DBDELETEEXISTS=true
fi

if [ x"$DBDELETEEXISTS" = xtrue ]; then
    echo "Are you sure you want to delete $DBNAME ? (y/n)"
    read DBDELETEEXISTS
    if [ x"$DBDELETEEXISTS" = xy ]; then
        DBDELETEEXISTS=true
    else
        DBDELETEEXISTS=false
    fi
fi

function operate_db() {
    sql=$1

    if [ -z "$sql" ]; then
        return
    fi

    echo "Run SQL: $sql with $DBUSERNAME - $DBPASSWORD"

    mysql -u$DBUSERNAME -p$DBPASSWORD -e "
        tee /tmp/dbsql_temp.log
        $sql;
        notee
        quit"

#    if [ -f "/tmp/dbsql_temp.log" ]; then
#        cat /tmp/dbsql_temp.log >> $DBLOG
#    fi
}

function delete_db() {
    db=$1
    
    if [ -z $db ]; then
        return
    fi

sql="DROP DATABASE IF EXISTS $db; 
SHOW DATABASES;"
operate_db "$sql"
}

function use_db() {
    db=$1
    
    if [ -z $db ]; then
        return
    fi

    sql="USE $db; SHOWTABLES $db"
    operate_db "$sql"
}

function create_db() {
    db=$1
    
    if [ -z $db ]; then
        return
    fi

    sql="CREATE DATABASE IF NOT EXISTS $db;
         SHOW DATABASES; USE $db; SHOW TABLES"
    operate_db "$sql"
}

if [ $DBDELETEEXISTS ]; then
    delete_db $DBNAME
fi

create_db $DBNAME

function delete_table() {
    tablle=$1

    if [ -z $table ]; then
        return
    fi

    sql="USE $DBNAME; DROP TABLE IF EXISTS $table; 
         SHOW TABLES";
    operate_db $sql
}

function create_table() {
    table=$1
    cols=$2

    if [ -z $table -o -z "$cols" ]; then
        return
    fi

    sql="USE $DBNAME; CREATE TABLE IF NOT EXISTS 
        $table ($cols) CHARACTER SET = 'utf8';
        SHOW FIELDS FROM $table"
    operate_db "$sql"
}

function add_table_constraint() {
    table=$1
    constraint=$2

    if [ -z $table -o -z "$constraint" ]; then
        return
    fi

    sql="USE $DBNAME; ALTER TABLE $table $constraint;
        SHOW FIELDS FROM $table"
    operate_db "$sql"
}

function insert_value() {
    table=$1
    variables=$2
    values=$3

    if [ -z $table -o -z "$values" ]; then
        return
    fi

    sql="USE $DBNAME; INSERT INTO $table ($variables) VALUES ($values);
        SELECT * FROM $table"
    operate_db "$sql"
}

function init_user_table() {
    create_table user \
        "uid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        sno CHAR(20),
        turename CHAR(20),
        password CHAR(50)"

        insert_value user "uid, turename, sno, password"  "'','周键', '20114842573', '142013'"
        insert_value user "uid, turename, sno, password"  "'','黄洁', '20114832034', '100011'"
        insert_value user "uid, turename, sno, password"  "'','殷晓翔', '20114831877', '034211'"
        insert_value user "uid, turename, sno, password"  "'','王来勇', '20134832875', '206575'"
        insert_value user "uid, turename, sno, password"  "'','蒋意庭', '20134832886', '221023'"
        insert_value user "uid, turename, sno, password"  "'','柴守斌', '20134832905', '048414'"
        insert_value user "uid, turename, sno, password"  "'','石炳辉', '20134833019', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','吴斌', '20134832375', '092819'"
        insert_value user "uid, turename, sno, password"  "'','朱维康', '20134833136', '017215'"
        insert_value user "uid, turename, sno, password"  "'','姚英杰', '20134833175', '167418'"
        insert_value user "uid, turename, sno, password"  "'','姚磊', '20134833247', '143436'"
        insert_value user "uid, turename, sno, password"  "'','柳金', '20134833284', '252315'"
        insert_value user "uid, turename, sno, password"  "'','杨振东', '20134833385', '271732'"
        insert_value user "uid, turename, sno, password"  "'','卢星宏', '20134833396', '222458'"
        insert_value user "uid, turename, sno, password"  "'','林卫', '20134833415', '010616'"
        insert_value user "uid, turename, sno, password"  "'','张涛', '20134833457', '246816'"
        insert_value user "uid, turename, sno, password"  "'','李亚敏', '20134833465', '057649'"
        insert_value user "uid, turename, sno, password"  "'','郭平平', '20134833476', '293027'"
        insert_value user "uid, turename, sno, password"  "'','王希收', '20134833569', '296915'"
        insert_value user "uid, turename, sno, password"  "'','柴仙', '20134833574', '149585'"
        insert_value user "uid, turename, sno, password"  "'','王昊海', '20134833989', '270015'"
        insert_value user "uid, turename, sno, password"  "'','刘远志', '20134834005', '083831'"
        insert_value user "uid, turename, sno, password"  "'','刘伟', '20134834034', '086332'"
        insert_value user "uid, turename, sno, password"  "'','徐毅鑫', '20134834135', '279213'"
        insert_value user "uid, turename, sno, password"  "'','曹丰年', '20134834146', '213814'"
        insert_value user "uid, turename, sno, password"  "'','王学伟', '20134834185', '093958'"
        insert_value user "uid, turename, sno, password"  "'','胡晓婷', '20134833625', '172221'"
        insert_value user "uid, turename, sno, password"  "'','张易', '20134833797', '280053'"
        insert_value user "uid, turename, sno, password"  "'','黎明辉', '20134833846', '272139'"
        insert_value user "uid, turename, sno, password"  "'','张思瑶', '20134831826', '206535'"
        insert_value user "uid, turename, sno, password"  "'','宋斌', '20134831844', '184016'"
        insert_value user "uid, turename, sno, password"  "'','李云飞', '20134831924', '219217'"
        insert_value user "uid, turename, sno, password"  "'','缪寀丰', '20134831945', '100555'"
        insert_value user "uid, turename, sno, password"  "'','梁佳博', '20134831995', '261116'"
        insert_value user "uid, turename, sno, password"  "'','刘小叶', '20134832035', '084585'"
        insert_value user "uid, turename, sno, password"  "'','殷魁', '20134832176', '011138'"
        insert_value user "uid, turename, sno, password"  "'','赵纯艺', '20134832354', '261915'"
        insert_value user "uid, turename, sno, password"  "'','蒋莉铭', '20134830879', '025227'"
        insert_value user "uid, turename, sno, password"  "'','杨柳', '20134830897', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','胡一凡', '20134830909', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','程琪媛', '20134830977', '201126'"
        insert_value user "uid, turename, sno, password"  "'','方来凯', '20134831004', '233111'"
        insert_value user "uid, turename, sno, password"  "'','雷富龙', '20134831067', '208581'"
        insert_value user "uid, turename, sno, password"  "'','孙金行', '20134831116', '123039'"
        insert_value user "uid, turename, sno, password"  "'','李如意', '20134831134', '219323'"
        insert_value user "uid, turename, sno, password"  "'','李辉', '20134831155', '928011'"
        insert_value user "uid, turename, sno, password"  "'','杨帆', '20134830026', '152071'"
        insert_value user "uid, turename, sno, password"  "'','王浩', '20134830044', '105413'"
        insert_value user "uid, turename, sno, password"  "'','陈可杨', '20134830065', '151413'"
        insert_value user "uid, turename, sno, password"  "'','周博开', '20134830156', '300236'"
        insert_value user "uid, turename, sno, password"  "'','陈晓京', '20134830169', '277078'"
        insert_value user "uid, turename, sno, password"  "'','毛娜娜', '20134830174', '155029'"
        insert_value user "uid, turename, sno, password"  "'','陶小平', '20134830187', '157111'"
        insert_value user "uid, turename, sno, password"  "'','于金丽', '20134830254', '291229'"
        insert_value user "uid, turename, sno, password"  "'','安洋洋', '20134830305', '317288'"
        insert_value user "uid, turename, sno, password"  "'','刘明钧', '20134830347', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','关思粤', '20134830379', '113617'"
        insert_value user "uid, turename, sno, password"  "'','戚春旭', '20134830409', '210019'"
        insert_value user "uid, turename, sno, password"  "'','蒋逸欣', '20134831357', '093915'"
        insert_value user "uid, turename, sno, password"  "'','胡威', '20134831419', '200315'"
        insert_value user "uid, turename, sno, password"  "'','王婉清', '20134831474', '83764'"
        insert_value user "uid, turename, sno, password"  "'','王晶晶', '20134831567', '220629'"
        insert_value user "uid, turename, sno, password"  "'','汤力', '20134831647', '306317'"
        insert_value user "uid, turename, sno, password"  "'','金瞳', '20134831684', '023725'"
        insert_value user "uid, turename, sno, password"  "'','孙泽', '20134831697', '044313'"
        insert_value user "uid, turename, sno, password"  "'','王琦', '20134831764', '058221'"
        insert_value user "uid, turename, sno, password"  "'','张耀文', '20134830427', '142038'"
        insert_value user "uid, turename, sno, password"  "'','刘桂松', '20134830485', '111576'"
        insert_value user "uid, turename, sno, password"  "'','童宏祥', '20134830496', '201353'"
        insert_value user "uid, turename, sno, password"  "'','徐雪年', '20134830526', '101688'"
        insert_value user "uid, turename, sno, password"  "'','蔡祺禄', '20134830539', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','王鹏', '20134830544', '161817'"
        insert_value user "uid, turename, sno, password"  "'','张杰', '20134830656', '103015'"
        insert_value user "uid, turename, sno, password"  "'','段文雪', '20134830754', '15552X'"
        insert_value user "uid, turename, sno, password"  "'','尹波', '20134832416', '145017'"
        insert_value user "uid, turename, sno, password"  "'','刘艺', '20134832447', '203971'"
        insert_value user "uid, turename, sno, password"  "'','潘志强', '20134832497', '110010'"
        insert_value user "uid, turename, sno, password"  "'','殷鹏', '20134832564', '150012'"
        insert_value user "uid, turename, sno, password"  "'','舒婷婷', '20134832577', 'NULL'"
        insert_value user "uid, turename, sno, password"  "'','马博', '20153410583', '291915'"
        insert_value user "uid, turename, sno, password"  "'','高彦强', '20153410590', '171617'"

        operate_db "USE 'cloud_note_db';UPDATE user SET password=md5(password)"
}

init_user_table

